name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19 # 使用しているGoのバージョンを指定

      - name: Install golangci-lint
        run: |
          curl -sSf https://install.golangci-lint | sh
          sudo mv golangci-lint /usr/local/bin

      - name: Run golangci-lint
        run: golangci-lint
